services:
  orchestrator:
    build:
      context: .
      dockerfile: src/orchestrator/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - AGENT_IMAGE=webdev-agent:latest
      - AGENT_OUTPUT_DIR=/tmp/agent_jobs
      - RETENTION_DAYS=1
    volumes:
      - agent_outputs:/tmp/agent_jobs
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - webdev_agent_builder

  webdev_agent_builder:
    build:
      context: .
      dockerfile: src/agent_containers/webdev_agent/Dockerfile
    image: webdev-agent:latest
    command: ["echo", "webdev-agent image built successfully"]

volumes:
  agent_outputs:
